// <auto-generated />
using BlazorAds.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAds.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221201012227_SeedMorePosts")]
    partial class SeedMorePosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAds.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Готовые сборки",
                            Url = "prefabricated-computer-assemblies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Компоненты по отдельности",
                            Url = "components-separately"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Переферия",
                            Url = "peripherals"
                        });
                });

            modelBuilder.Entity("BlazorAds.Shared.Poster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Продам свой личный пк в полном комплекте! В состоянии нового, собирал около месяца назад, все коробки и чеки имеются, все на гарантии кроме монитора и видеокарты ( т.к и то, и другое заказывал с америки, видеокарта в превосходном состоянии, на пломбе, без шумов, с пассивным охлаждением работающим, вертушки крутятся максимально тихо и быстро, по монитору особо сказать нечего, без всяких засветов, битых пикселей и прочего, четкая картинка 1920х1080 ) От себя на видеокарту и монитор дам гарантию 60 дней! Любые проверки от вас по факту только порадуют, компьютер тянет абсолютно все игры на высоких-максимальных, при покупке сразу переустановим виндовс (потому что сейчас мои данные на компьютере), сделаем драйвера и все в этом духе. Живу в Академическом, адрес в обьявлении правильный. В комплект входит - монитор, колонки, игровые наушники с микрофоном, вебкамера 720р, клавиатура, мышь, коврик для мыши игровой, системный блок, и естественно все кабели.",
                            ImageUrl = "https://52.img.avito.st/image/1/1.bRk9Yba6wfALyAP1a1QBWPzCx_SJQskyjMLF-IHKww.4zFAWqfk8mp-af46F8N0cqqoHulRiQLGdQeKzoYjdPg",
                            Price = 44999m,
                            Title = "Игровой пк Полный Комплект"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Нa вcе HОУTБУKИ пpедocтавляeтcя ГАРAHTИЯ! Пpоводим пoлнoценноe теxническоe обслуживание и предпродажное тестирование каждого ноутбука",
                            ImageUrl = "https://87.img.avito.st/image/1/1.JnzoMba6ipXemEiQqDlVMSmSjJFcEoJXWZKOnVSaiA.zimulSF4iWMwSOQgCrboVNhm4SeohyWaO-GMR03e4Jw",
                            Price = 9990m,
                            Title = "Офисный пк i5-2320/4GB/1TB/Intel HD"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Не вскрывалась, не перегревалась, не разгонялась, в майнинге не участвовала. Как новая, коробка чек имеется, гарантия ещё 10 месяцев.",
                            ImageUrl = "https://42.img.avito.st/image/1/1.QyAbGra678ktsy3MEXdKUtq56c2vOecLqrnrwaex7Q.yRiKb99iuPc_ui9LJoBva1rWA08vZXN222upEi1XJfI",
                            Price = 14000m,
                            Title = "Видеокарта asus GTX 1650 Super"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Процессор в рабочем состоянии",
                            ImageUrl = "https://46.img.avito.st/image/1/1.__R8Ara6Ux1Kq5EYDkHn2LyhVRnIIVvfzaFXFcCpUQ.-qPwDpwWaj3_Lt9MFnhfDjAA2tgZHH3RiRDpyeG510M",
                            Price = 3000m,
                            Title = "Процессор ryzen 3 1200 OEM"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Монитор в отличном состоянии. Адаптер и hdmi в комплекте.",
                            ImageUrl = "https://00.img.avito.st/image/1/1.NbBMJ7a6mVl6jltcKg8JnIyEn134BJGb_YSdUfCMmw.E7MPTOUDNa3k2ucIsPKyRR2HJCCbMuZQb1M72vi8L6I",
                            Price = 7000m,
                            Title = "Монитор samsung s24e390hl"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Как новая. Вообще не пользовался",
                            ImageUrl = "https://65.img.avito.st/image/1/1.9OrODra6WAP4p5oGqlnJrA-tXgd6LVDBf61cC3KlWg.thbpmBqxTM4_5a2jxntwKaquBUvyyi-gC1T2U9yzHJQ",
                            Price = 150m,
                            Title = "Компьютерная мышка"
                        });
                });

            modelBuilder.Entity("BlazorAds.Shared.Poster", b =>
                {
                    b.HasOne("BlazorAds.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
